{% set name = "deutschland" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deutschland-{{ version }}.tar.gz
  sha256: 81a1cb5ace07356c40b21bdad78013c326ef971f58cad00d5088abeab6526fff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - requests >=2.26.0,<3.0.0
    - dateparser >=1.0.0,<2.0.0
    - beautifulsoup4 >=4.9.3,<5.0.0
    - more-itertools >=8.10.0,<9.0.0
    - numpy >=1.19.0,<2.0.0
    - pillow >=10.0.0,<11.0.0
    - mapbox-vector-tile >=2.0.1,<3.0.0
    - lxml >=4.9.3,<5.0.0
    - pandas *
    - onnxruntime >1.10.0,!=1.16.0
    - de-autobahn >=1.0.4,<2.0.0
    - de-bundesrat >=0.1.0,<0.2.0
    - de-bundestag >=0.1.0,<0.2.0
    - de-dwd >=1.0.1,<2.0.0
    - de-interpol >=0.1.0,<0.2.0
    - de-jobsuche >=0.1.0,<0.2.0
    - de-ladestationen >=1.0.5,<2.0.0
    - de-mudab >=0.1.0,<0.2.0
    - de-nina >=1.0.1,<2.0.0
    - de-polizei-brandenburg >=0.1.0,<0.2.0
    - de-risikogebiete >=0.1.0,<0.2.0
    - de-smard >=0.1.0,<0.2.0
    - de-strahlenschutz >=1.0.0,<2.0.0
    - de-travelwarning >=0.1.0,<0.2.0
    - de-zoll >=0.1.0,<0.2.0
  run_constrained:
    - de-ausbildungssuche >=0.1.0,<0.2.0
    - de-berufssprachkurssuche >=0.1.0,<0.2.0
    - de-bundestag-lobbyregister >=0.1.0,<0.2.0
    - de-coachingangebote >=0.1.0,<0.2.0
    - de-dip-bundestag >=0.1.0,<0.2.0
    - de-entgeltatlas >=0.1.0,<0.2.0
    - de-hochwasserzentralen >=0.1.0,<0.2.0
    - de-pegel-online >=0.1.0,<0.2.0
    - de-pflanzenschutzmittelzulassung >=0.1.0,<0.2.0
    - de-studiensuche >=0.1.0,<0.2.0
    - de-tagesschau >=0.1.0,<0.2.0
    - de-weiterbildungssuche >=0.1.0,<0.2.0
    - de-feiertage >=1.0.1,<2.0.0
    - de-marktstammdaten >=0.1.0,<0.2.0
    - de-vag >=0.1.0,<0.2.0
    - de-abfallnavi >=0.1.0,<0.2.0
    - de-bundeshaushalt >=1.0.0,<2.0.0
    - de-ecovisio >=0.1.0,<0.2.0
    - de-dashboarddeutschland >=0.1.0,<0.2.0
    - de-destatis >=0.1.0,<0.2.0

test:
  imports:
    - deutschland.bundesanzeiger
    - deutschland.bundesnetzagentur
    - deutschland.bundeswahlleiter
    - deutschland.lebensmittelwarnung
    - deutschland.verena
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bundesAPI/deutschland
  summary: Die wichtigsten APIs Deutschlands in einem Python Paket.
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
